name: SSB Industry Tracker
on: 
  workflow_dispatch:
  schedule:
    - cron: "5 12 * * *"
jobs:
  build-and-deploy:
    runs-on: Ubuntu-20.04
    steps:
      - name: Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Update SSB Industry Tracker
        if: always()
        env: 
          DW_TOKEN: ${{ secrets.DW_TOKEN }}
        run: python SSB_Industry_Tracker.py
      - name: Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
